### ISSUE TITLE
Getting version error during pod install

### ISSUE THREAD

**Issue by gilteitelbaum** [getbouncer/react-native-cardscan#153] opened 2021-09-26 10:23 UTC
I am getting the following error when I attempt to do a pod install.

`[!] CocoaPods could not find compatible versions for pod "CardScan":
  In Podfile:
    CardScan

    react-native-cardscan (from `../../js/node_modules/react-native-cardscan`) was resolved to 1.1.30, which depends on
      CardScan (~> 2.0.9)

Specs satisfying the `CardScan, CardScan (~> 2.0.9)` dependency were found, but they required a higher minimum deployment target.
`

Taking a look - the podspec file requires a version of 2.0.9 or greater, while the library included here is version 1.1.30

**Comment by kingst** [comment] 2021-09-26 14:37
It sounds like the issue is with the Podspec itself. CardScan 2.0.9 has a minimum deploy target of iOS version 11.0, what do you have set in yours for your app? Here's the relevant line in the CardScan podspec:

> s.ios.deployment_target = '11.0'

**Comment by gilteitelbaum** [comment] 2021-09-29 09:48
Where exactly do I find this podspec file?

I did see that our PodFile had the following version

platform :ios, '10'

But when I changed it to 11, I got an error saying "Undefined symbol: _RCTRegisterModule"

**Comment by kingst-stripe** [comment] 2021-09-30 20:58
I'm looking into this, I'll have some guidance soon on how to work around this

**Comment by kingst-stripe** [comment] 2021-09-30 22:40
I tried changing the example app's Podfile to `platform: ios, '10'` and I got a warning but the system still built and worked. As long as you use the `Cardscan.isSupportedAsync()` method to make sure that the system is supported at runtime it is safe.

Were you getting a build error or was it just a warning? If it was just a warning you can ignore it.

**Comment by kingst-stripe** [comment] 2021-10-02 11:07
I'm going to close this ticket, but if your issue isn't solved please re-open it and I can continue to dig in, but from what I can tell it's just a warning that you can safely ignore.

**Closed by kingst-stripe** 2021-10-02 11:07 UTC
